
name: sonarqube

services:
  sonarqube:
    image: registry.cn-chengdu.aliyuncs.com/seanly/appset:sonarqube-9.9.8-community-1-arm64
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - discovery.type=single-node
      - SONAR_AUTHENTICATOR_DOWNCASE=true
      - SONAR_UPDATECENTER_ACTIVATE=false
      - SONAR_WEB_JAVAOPTS: '-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=*:5005,suspend=n'
    volumes:
      - sonarqube-data:/opt/sonarqube/data

volumes:
  sonarqube-data: